from tkinter import * 
from PIL import ImageTk ,Image  
from tkinter import ttk

root = Tk()

def getvals():
    print("submitting form")
    Pout = Pvalue.get()
    Nout = Nvalue.get()
    Kout = Kvalue.get()
    Marketout = Marketvalue.get()
    dayout =Dayvalue.get()
    monthout = Monthvalue.get()
    print(monthout)
    Invout = Investvalue.get()
    hectout = Landvalue.get()
    Price = 1.15*Invout/1.3*hectout
    sum = Pout + Nout
    sum = str(sum)
    print(Marketout)
    
    final.config(text="The sum of values is"+sum)
    return [Pout,Nout]

#GUI logic
root.geometry("1000x450")
root.minsize(250,100)
root.maxsize(1900,1000)

# f1 = Frame(root,bg="black",borderwidth=6)
# f1.grid()

#Title is given here
title1 = Label(root,text="Crop Predictor")
title1.place(relx=0.5,rely=0.01,anchor=CENTER)

#making all the labels
N = Label(root,text="""Enter Nitrogen content in soil:""")
P = Label(root,text="""Enter Phosphorus content in soil:""")
K = Label(root,text="""Enter Potassium content in soil:""")
Ph = Label(root,text="""Enter Ph Value of the soil:""")
Month = Label(root,text="""Enter the month """)
Day = Label(root,text="Enter the day")
Land = Label(root,text="""Enter your Land Size in hectares""")
invest = Label(root, text="""Enter the amount you can invest""")
district = Label(root,text="Enter your district")
market = Label(root,text="Choose prefered market")
final = Label(root,text = "")

# States = []

#placing the things on thw window
N.place(relx=0.01,rely=0.2,anchor=W)
P.place(relx=0.01,rely=0.3,anchor=W)
K.place(relx=0.01,rely=0.4,anchor=W)
Ph.place(relx=0.01,rely=0.5,anchor=W)
Land.place(relx=0.01,rely=0.6,anchor=W)
Month.place(relx=0.01,rely=0.7,anchor=W)
Day.place(relx=0.01,rely=0.8,anchor=W)
invest.place(relx=0.5,rely=0.2,anchor=W)
district.place(relx=0.8,rely=0.3,anchor=W)
market.place(relx = 0.5,rely=0.3,anchor=W)
final.place(relx=0.5,rely=0.8,anchor=W)

#tkinter variable 
Nvalue = IntVar()
Pvalue = IntVar()
Kvalue = IntVar()
Phvalue = DoubleVar()
Monthvalue = IntVar()
Dayvalue = IntVar()
Investvalue = DoubleVar()
District = StringVar()
Landvalue = DoubleVar()
Marketvalue = StringVar()

#entry field
Nentry = Entry(root,textvariable=Nvalue)
Pentry = Entry(root,textvariable=Pvalue)
Kentry = Entry(root,textvariable=Kvalue)
Phentry = Entry(root,textvariable=Phvalue)
Monthentry = Entry(root,textvariable=Monthvalue)
Dayentry = Entry(root,textvariable=Dayvalue)
Investentry = Entry(root,textvariable=Investvalue)
Landentry = Entry(root,textvariable=Landvalue)
District = ttk.Combobox(root,textvariable=District) 
Market = ttk.Combobox(root,textvariable=Marketvalue)

#plot the entry thing
Nentry.place(relx=0.3,rely=0.2,anchor=W)
Pentry.place(relx=0.3,rely=0.3,anchor=W)
Kentry.place(relx=0.3,rely=0.4,anchor=W)
Phentry.place(relx=0.3,rely=0.5,anchor=W)
Monthentry.place(relx=0.3,rely=0.7,anchor=W)
Dayentry.place(relx=0.3,rely=0.8,anchor=W)
Investentry.place(relx=0.7,rely=0.2,anchor=W)
Landentry.place(relx=0.3,rely=0.6,anchor=W)

District['values'] = ["NICOBAR","SOUTH ANDAMAN","N & M ANDAMAN","LOHIT","EAST SIANG","SUBANSIRI F.D","TIRAP","ANJAW (LOHIT)","LOWER DIBANG",
                      "CHANGLANG","PAPUM PARE","LOW SUBANSIRI","UPPER SIANG","WEST SIANG","DIBANG VALLEY","WEST KAMENG","EAST KAMENG",
                      "TAWANG(W KAME)","KURUNG KUMEY","CACHAR","DARRANG","GOALPARA","KAMRUP","LAKHIMPUR","NORTH CACHAR","NAGAON","SIVASAGAR",
                      "BARPETA","DHUBRI","DIBRUGARH","JORHAT","KARIMGANJ","KOKRAJHAR","SHONITPUR","GOLAGHAT","TINSUKIA","DHEMAJI(LAKHI)",
                      "KARBI ANGLONG","UDALGURI(DARA)","KAMRUP METROP","CHIRANG(BONGAI)","BAKSA BARPETA","BONGAIGAON","MORIGAON","NALBARI",
                      "EAST KHASI HI","JAINTIA HILLS","EAST GARO HIL","RI-BHOI","SOUTH GARO HI","W KHASI HILL","WEST GARO HIL","IMPHAL EAST",
                      "SENAPATI","TAMENGLONG","CHANDEL","UKHRUL","THOUBAL","BISHNUPUR","IMPHAL WEST","CHURACHANDPUR","AIZAWL","CHAMPHAI",
                      "KOLASIB","LUNGLEI","CHHIMTUIPUI","LAWNGTLAI","SAIHA","SERCHHIP","KOHIMA","TUENSANG","MOKOKCHUNG","DIMAPUR","WOKHA",
                      "MON","ZUNHEBOTO","PHEK","KEPHRIE","LONGLENG","PEREN","NORTH TRIPURA","SOUTH TRIPURA","WEST TRIPURA","DHALAI","COOCH BEHAR",
                      "DARJEELING","JALPAIGURI","MALDA","SOUTH DINAJPUR","NORTH DINAJPUR","NORTH SIKKIM","EAST SIKKIM","WEST SIKKIM","SOUTH SIKKIM",
                      "BANKURA","BIRBHUM","BURDWAN","HOOGHLY","HOWRAH","PURULIA","MURSHIDABAD","NADIA","NORTH 24 PARG","SOUTH 24 PARG","EAST MIDNAPOR",
                      "WEST MIDNAPOR","KOLKATA","BALASORE","BOLANGIR","KANDHAMAL/PHU","CUTTACK","DHENKANAL","GANJAM","KALAHANDI","KEONDJHARGARH",
                      "KORAPUT","MAYURBHANJ","PURI","SAMBALPUR","SUNDARGARH","BHADRAK","JAJPUR","KENDRAPARA","ANGUL","NAWAPARA","MALKANGIRI",
                      "NAWARANGPUR","NAYAGARH","KHURDA","BARGARH","JHARSUGUDA","DEOGARH","RAYAGADA","GAJAPATI","JAGATSINGHAPU","BOUDHGARH",
                      "SONEPUR","BOKARO","DHANBAD","DUMKA","HAZARIBAG","PALAMU","RANCHI","SAHIBGANJ","WEST SINGHBHUM","DEOGHAR","GIRIDIH",
                      "GODDA","GUMLA","LOHARDAGA","CHATRA","KODERMA","PAKUR","EAST SINGHBHU","GARHWA","SERAIKELA-KHA","JAMTARA","LATEHAR",
                      "SIMDEGA","KHUNTI(RANCHI","RAMGARH","BHAGALPUR","EAST CHAMPARAN","DARBHANGA","GAYA","MUNGER","MUZAFFARPUR","WEST CHAMPARAN",
                      "PURNEA","GOPALGANJ","MADHUBANI","AURANGABAD","BEGUSARAI","BHOJPUR","NALANDA","PATNA","KATIHAR","KHAGARIA","SARAN","MADHEPURA",
                      "NAWADA","ROHTAS","SAMASTIPUR","SITAMARHI","SIWAN","VAISHALI","JAHANABAD","BUXAR","ARARIA","BANKA","BHABUA","JAMUI",
                      "KISHANGANJ","SHEIKHPURA","SUPAUL","LAKHISARAI","SHEOHAR","ARWAL","SAHARSA","ALLAHABAD","AZAMGARH","BAHRAICH","BALLIA",
                      "BANDA","BARABANKI","BASTI","DEORIA","FAIZABAD","FARRUKHABAD","FATEHPUR","GHAZIPUR","GONDA","GORAKHPUR","HARDOI","JAUNPUR",
                      "KANPUR NAGAR","KHERI LAKHIMP","LUCKNOW","MIRZAPUR","PRATAPGARH","RAE BARELI","SITAPUR","SULTANPUR","UNNAO","VARANASI",
                      "SONBHADRA","MAHARAJGANJ","MAU","SIDDHARTH NGR","KUSHINAGAR","AMBEDKAR NAGAR","KANNAUJ","BALRAMPUR","KAUSHAMBI","SAHUJI MAHARA",
                      "KANPUR DEHAT","CHANDAULI","SANT KABIR NGR","SANT RAVIDAS","SHRAVASTI NGR","AGRA","ALIGARH","BAREILLY","BIJNOR","BADAUN",
                      "BULANDSHAHAR","ETAH","ETAWAH","HAMIRPUR","JALAUN","JHANSI","LALITPUR","MAINPURI","MATHURA","MEERUT","MORADABAD","MUZAFFARNAGAR",
                      "PILIBHIT","RAMPUR","SAHARANPUR","SHAHJAHANPUR","GHAZIABAD","FIROZABAD","MAHOBA","MAHAMAYA NAGA","AURAIYA","BAGPAT","JYOTIBA PHULE",
                      "GAUTAM BUDDHA","KANSHIRAM NAG","ALMORA","CHAMOLI","DEHRADUN","GARHWAL PAURI","NAINITAL","PITHORAGARH","GARHWAL TEHRI","UTTARKASHI",
                      "HARIDWAR","CHAMPAWAT","RUDRAPRAYAG","UDHAM SINGH N","BAGESHWAR","AMBALA","GURGAON","HISAR","JIND","KARNAL","MAHENDRAGARH","ROHTAK",
                      "BHIWANI","FARIDABAD","KURUKSHETRA","SIRSA","SONEPAT(RTK)","YAMUNANAGAR","KAITHAL","PANIPAT","REWARI","FATEHABAD","JHAJJAR","PANCHKULA",
                      "MEWAT","PALWAL(FRD)","CHANDIGARH","NEW DELHI","CENTRAL DELHI","EAST DELHI","NORTH DELHI","NE DELHI","SW DELHI","NW DELHI","SOUTH DELHI",
                      "WEST DELHI","AMRITSAR","BATHINDA","FEROZEPUR","GURDASPUR","HOSHIARPUR","JALANDHAR","KAPURTHALA","LUDHIANA","PATIALA","RUPNAGAR",
                      "SANGRUR","FARIDKOT","MOGA","NAWANSHAHR",
"FATEHGARH SAH",
"MUKTSAR",
"MANSA",
"BARNALA",
"SAS NAGAR(MGA)",
"TARN TARAN",
"BILASPUR",
"CHAMBA",
"KANGRA",
"KINNAUR",
"KULLU",
"LAHUL & SPITI",
"MANDI",
"SHIMLA",
"SIRMAUR",
"SOLAN",
"UNA",
"ANANTNAG",
"BARAMULLA",
"DODA",
"JAMMU",
"KATHUA",
"LADAKH (LEH)",
"UDHAMPUR",
"BADGAM",
"KUPWARA",
"PULWAMA",
"SRINAGAR",
"KARGIL",
"POONCH",
"RAJOURI",
"BANDIPORE",
"GANDERWAL",
"KULGAM/(ANT)",
"SHOPAN",
"SAMBA",
"KISTWAR",
"REASI",
"RAMBAN(DDA)",
"BARMER",
"BIKANER",
"CHURU",
"SRI GANGANAGA",
"JAISALMER",
"JALORE",
"JODHPUR",
"NAGAUR",
"PALI",
"HANUMANGARH",
"AJMER",
"ALWAR",
"BANSWARA",
"BHARATPUR",
"BHILWARA",
"BUNDI",
"CHITTORGARH",
"DUNGARPUR",
"JAIPUR",
"JHALAWAR",
"JHUNJHUNU",
"KOTA",
"SAWAI MADHOPUR",
"SIKAR",
"SIROHI",
"TONK",
"UDAIPUR",
"DHOLPUR",
"BARAN",
"DAUSA",
"RAJSAMAND",
"KARAULI",
"PRATAPGARH(CHT",
"BETUL",
"VIDISHA",
"BHIND",
"DATIA",
"DEWAS",
"DHAR",
"GUNA",
"GWALIOR",
"HOSHANGABAD",
"INDORE",
"JHABUA",
"MANDSAUR",
"MORENA",
"KHANDWA",
"KHARGONE",
"RAISEN",
"RAJGARH",
"RATLAM",
"SEHORE",
"SHAJAPUR",
"SHIVPURI",
"UJJAIN",
"BHOPAL",
"HARDA",
"NEEMUCH",
"SHEOPUR",
"BARWANI",
"ASHOKNAGAR(GNA",
"BURHANPUR",
"ALIRAJPUR(JBA)",
"BALAGHAT",
"CHHATARPUR",
"CHHINDWARA",
"JABALPUR",
"MANDLA",
"NARSINGHPUR",
"PANNA",
"REWA",
"SAGAR",
"SATNA",
"SEONI",
"SHAHDOL",
"SIDHI",
"TIKAMGARH",
"KATNI",
"DINDORI",
"UMARIA",
"DAMOH",
"ANUPPUR(SHAHD",
"SINGRAULI",
"AHMEDABAD",
"BANASKANTHA",
"BARODA",
"BHARUCH",
"VALSAD",
"DANGS",
"KHEDA",
"MEHSANA",
"PANCHMAHALS",
"SABARKANTHA",
"SURAT",
"GANDHINAGAR",
"NARMADA(BRC)",
"NAVSARI(VSD)",
"ANAND(KHR)",
"PATAN(MHSN)",
"DAHOD(PNML)",
"TAPI(SRT)",
"AMRELI",
"BHAVNAGAR",
"JAMNAGAR",
"JUNAGADH",
"KUTCH",
"RAJKOT",
"SURENDRANAGAR",
"PORBANDAR",
"DNH",
"DAMAN",
"DIU",
"MUMBAI CITY",
"RAIGAD",
"RATNAGIRI",
"THANE",
"SINDHUDURG",
"MUMBAI SUB",
"NORTH GOA",
"SOUTH GOA",
"AHMEDNAGAR",
"DHULE",
"JALGAON",
"KOLHAPUR",
"NASHIK",
"PUNE",
"SANGLI",
"SATARA",
"SOLAPUR",
"NANDURBAR",
"BEED",
"NANDED",
"OSMANABAD",
"PARBHANI",
"LATUR",
"JALNA",
"HINGOLI",
"AKOLA",
"AMRAVATI",
"BHANDARA",
"BULDHANA",
"CHANDRAPUR",
"NAGPUR",
"YAVATMAL",
"WARDHA",
"GADCHIROLI",
"WASHIM",
"GONDIA",
"BASTAR",
"DURG",
"RAIGARH",
"RAIPUR",
"SURGUJA",
"RAJNANDGAON",
"DANTEWADA",
"KANKER (NORH",
"JANJGIR-CHAMP",
"KORBA",
"JASHPUR",
"DHAMTARI",
"MAHASAMUND",
"KORIYA",
"KOWARDHA (KAB",
"NARAYANPUR",
"BIJAPUR",
"EAST GODAVARI",
"WEST GODAVARI",
"GUNTUR",
"KRISHNA",
"NELLORE",
"PRAKASAM",
"SRIKAKULAM",
"VISAKHAPATNAM",
"VIZIANAGARAM",
"ADILABAD",
"HYDERABAD",
"KARIMNAGAR",
"KHAMMAM",
"MAHABUBNAGAR",
"MEDAK",
"NALGONDA",
"NIZAMABAD",
"WARANGAL",
"RANGAREDDY",
"ANANTAPUR",
"CHITTOOR",
"KUDDAPAH",
"KURNOOL",
"VELLORE",
"COIMBATORE",
"DHARMAPURI",
"KANYAKUMARI",
"CHENNAI",
"MADURAI",
"NILGIRIS",
"RAMANATHAPURA",
"SALEM",
"THANJAVUR",
"TIRUCHIRAPPAL",
"TIRUNELVELI",
"ERODE",
"PUDUKKOTTAI",
"DINDIGUL",
"VIRUDHUNAGAR",
"SIVAGANGA",
"THOOTHUKUDI",
"TIRUVANNAMALA",
"NAGAPATTINAM",
"VILUPPURAM",
"CUDDALORE",
"KANCHIPURAM",
"TIRUVALLUR",
"THENI",
"NAMAKKAL",
"KARUR",
"PERAMBALUR",
"TIRUVARUR",
"KRISHNAGIRI",
"ARIYALUR",
"TIRUPUR",
"PONDICHERRY",
"KARAIKAL",
"MAHE",
"YANAM",
"UTTAR KANNADA",
"DAKSHIN KANDA",
"UDUPI",
"BELGAM",
"BIDAR",
"DHARWAD",
"GULBARGA",
"YADGIR",
"RAICHUR",
"BAGALKOTE",
"GADAG",
"HAVERI",
"KOPPAL",
"BANGALORE RUR",
"BELLARY",
"CHIKMAGALUR",
"CHITRADURGA",
"KODAGU",
"HASSAN",
"KOLAR",
"MANDYA",
"MYSORE",
"SHIMOGA",
"TUMKUR",
"BANGALORE URB",
"CHAMARAJANAGA",
"DAVANGERE",
"RAMNAGAR(BNGR)",
"CHICKBALLAPUR",
"ALAPPUZHA",
"CANNUR",
"ERNAKULAM",
"KOTTAYAM",
"KOZHIKODE",
"MALAPPURAM",
"PALAKKAD",
"KOLLAM",
"THRISSUR",
"THIRUVANANTHA",
"IDUKKI",
"KASARGOD",
"PATHANAMTHITTA",
"WAYANAD","LAKSHADWEEP"]

Market['values']=["Port Blair",
"Kalikiri",
"Mulakalacheruvu",
"Vayalapadu",
"Banaganapalli",
"Attili",
"Cachar",
"Kharupetia",
"Gauripur",
"Jorhat",
"Pamohi(Garchuk)",
"Dhekiajuli",
"Jagdalpur",
"Charama",
"Lakhanpuri",
"Narharpur",
"Pratappur",
"Sanquelim",
"Damnagar",
"Khambhat(Grain Market)",
"Umreth",
"Ankleshwar",
"Bachau",
"Nadiyad(Chaklasi)",
"Gogamba",
"Gogamba(Similiya)",
"Bardoli(Katod)",
"Mandvi",
"S.Mandvi",
"Vyra",
"Bodeli",
"Bodeli(Hadod)",
"Bodeli(Kalediya)",
"Bodeli(Modasar)",
"Padra",
"Chikli(Khorgam)",
"Shahzadpur",
"Faridabad",
"Pataudi",
"Pipli",
"Taura",
"Madlauda",
"Kangra(Jaisinghpur)",
"Kangra(Jassour)",
"Palampur",
"Bhuntar",
"Zaloosa-Chararishrief (F&V)",
"Ramanagara",
"Kolar",
"Gubbi",
"Aroor",
"Chengannur",
"Mannar",
"Piravam",
"Taliparamba",
"Kasargod",
"Manjeswaram",
"Anchal",
"Chathanoor",
"Kaliyanchanda",
"Ettumanoor",
"Kottayam",
"Kondotty",
"Chelakkara",
"Irinjalakkuda",
"Kodungalloor",
"Maranelloor",
"Parassala",
"Jaithari",
"Sendhwa",
"Dhar",
"Dhar(F&V)",
"Gorakhpur",
"Thandla",
"Pandhana(F&V)",
"Gadarwada",
"Sheopurkalan",
"Syopurkalan(F&V)",
"Newasa(Ghodegaon)",
"Rahata",
"Deoulgaon Raja",
"Yawal",
"Kolhapur",
"Kolhapur(Malkapur)",
"Savner",
"Bhokar",
"Lasalgaon(Niphad)",
"Pune",
"Pune(Hadapsar)",
"Pune(Khadiki)",
"Pune(Pimpri)",
"Karad",
"Akluj",
"Mangal Wedha",
"Pandharpur",
"Bishenpur",
"Moreh",
"Lamlong Bazaar",
"Imphal",
"Thoubal",
"Shillong",
"Mangkolemba",
"Angul",
"Angul(Jarapada)",
"Pallahara",
"Jaleswar",
"Nilagiri",
"Godabhaga",
"Hindol",
"Kasinagar",
"Parlakhemundi",
"Bhanjanagar",
"Digapahandi",
"Jharsuguda",
"Betnoti",
"Saraskana",
"Nawarangpur",
"Bonai",
"Panposh",
"Karaikal",
"Chogawan",
"Mehta",
"Dhanaula",
"Bhucho",
"Dera Baba Nanak",
"Dhariwal",
"Kalanaur",
"Dasuya",
"Adampur",
"Lohian Khas",
"Mehatpur",
"Doraha",
"Sahnewal",
"Mansa",
"Malout",
"Ghanaur",
"Rajpura",
"Morinda",
"Harike",
"Patti",
"Anta",
"Barmer",
"Lunkaransar",
"Begu",
"Jalore",
"Khanpur",
"Itawa",
"Sri Madhopur",
"Surajgarh",
"Deoli",
"Uniyara",
"Anaimalai",
"Annur",
"Coimbatore",
"Karamadai",
"Madathukulam",
"Negamam",
"Palladam",
"Pethappampatti",
"Pollachi",
"Pongalur",
"Pudupalayam",
"Senjeri",
"Sevur",
"Thondamuthur",
"Udumalpet",
"Cuddalore",
"Kurinchipadi",
"Dharampuri",
"Palakode",
"Papparapatti",
"Pappireddipatti",
"Pennagaram",
"Gopalpatti",
"Palani",
"Dharapuram",
"Elumathur",
"Kodumudi",
"Kunnathur",
"Muthur",
"Vellakkoil",
"Acharapakkam",
"Chengalpattu",
"Gummidipoondy",
"Kanchipuram",
"Maduranthagam",
"Pallipattu",
"Ponner",
"Sunguvarchatram",
"Uthiramerur",
"Bargur",
"Pochampalli",
"Uthangarai",
"Melur",
"Thirumangalam",
"Kalliakavillai",
"Namagiripettai",
"Namakkal",
"Rasipuram",
"Tiruchengode",
"Velur",
"Sivagangai",
"Attur",
"Gangavalli",
"Karumanturai",
"Kolathur",
"Konganapuram",
"Omalur",
"Salem",
"Thalaivasal",
"Thammampati",
"Vazhapadi",
"Singampuneri",
"Budalur",
"Kumbakonam",
"Orathanadu",
"Papanasam",
"Thanjavur",
"Thiruppananthal",
"Vallam",
"Cheyyar",
"Ammoor",
"Kalavai",
"Vellore",
"Avalurpet",
"Chinnasalem",
"Gingee",
"Kallakurichi",
"Manalurpet",
"Sangarapuram",
"Tindivanam",
"Tiruvennainallur",
"Vikkiravandi",
"Villupuram",
"Rajapalayam",
"Sathur",
"Mahboob Manison",
"Koratla",
"Vemulawada",
"Madhira",
"Nalgonda",
"Ramannapet",
"Voligonda",
"Pitlam",
"Chevella",
"Dasda",
"Bishalgarh",
"Bishramganj",
"Barpathari",
"Achnera",
"Fatehabad",
"Jagnair",
"Jarar",
"Khairagarh",
"Samsabad",
"Atrauli",
"Sirsa",
"Bagpat",
"Baraut",
"Mihipurwa",
"Risia",
"Ruperdeeha",
"Chitwadagaon",
"Gopiganj",
"Divai",
"Gulavati",
"Siyana",
"Mau(Chitrakut)",
"Aliganj",
"Jasvantnagar",
"Kamlaganj",
"Bindki",
"Kishunpur",
"Javer",
"Hapur",
"Ait",
"Kadaura",
"Baruwasagar",
"Chirgaon",
"Chhibramau(Kannuj)",
"Rura",
"Mohammdi",
"Tikonia",
"Paliakala",
"Charkhari",
"Doharighat",
"Mirzapur",
"Sambhal",
"Muzzafarnagar",
"Shahpur",
"Thanabhawan",
"Lalganj",
"Milak",
"Chutmalpur",
"Devband",
"Gangoh",
"Nakud",
"Nanuta",
"Sultanpurchilkana",
"Jalalabad",
"Viswan",
"Dudhi",
"Robertsganj",
"Dehradoon",
"Kashipur",
"Bishnupur(Bankura)",
"Khatra",
"Asansol",
"Burdwan",
"Guskara(Burdwan)",
"Kalna",
"Katwa",
"Memari",
"Pandua",
"Dhupguri",
"Samsi",
"Ghatal",
"Beldanga",
"Jangipur",
"Nadia",
"Habra",
"Balarampur",
"Purulia",
"Baruipur(Canning)",
"Islampur","Raiganj"]
District.place(relx=0.8,rely=0.45,relheight=0.25,relwidth=0.15,anchor=W)
Market.place(relx=0.5,rely=0.45,relheight=0.25,relwidth=0.15,anchor =W)
# #label for the state
# ttk.Label(root, text = "Select the Month :")
# n = tk.StringVar()
# monthchoosen = ttk.Combobox(root, width = 27, textvariable = n)
# monthchoosen['values'] = ()
  
# monthchoosen.pack()
# monthchoosen.current()
Button(text="submit to get your ideal crop",command=getvals).place(relx=0.8,rely=0.7 , anchor=W)
listtemp = getvals()
root.mainloop() 